const { getErrorCode } = require('../utils/error-codes');
const https = require('https');
const path = require('path');
const fs = require('fs');

const API_ENDPOINT = 'https://www.googleapis.com/pagespeedonline/v5/runPagespeed';

function cleanValue(val) {
  if (!val || val === 'N/A') return val;
  return String(val).replace(/\u00A0/g, ' ').trim();
}

function fetchJson(urlObj) {
  return new Promise((resolve, reject) => {
    https.get(urlObj.toString(), (res) => {
      let data = '';
      res.on('data', chunk => data += chunk);
      res.on('end', () => {
        try { resolve(JSON.parse(data)); }
        catch (e) { reject(new Error('Invalid JSON response')); }
      });
    }).on('error', reject);
  });
}

function scoreColor(score) {
  if (score === 'N/A' || score === null || score === undefined) return '#aaa';
  const n = Number(score);
  if (n >= 90) return '#0cce6b';
  if (n >= 50) return '#ffa400';
  return '#ff4e42';
}

function buildScorecardHtml(domain, scores, metrics, strategy, apiUrl) {
  const scoreItems = [
    { label: 'Performance',    value: scores.performance },
    { label: 'Accessibility',  value: scores.accessibility },
    { label: 'Best Practices', value: scores.bestPractices },
    { label: 'SEO',            value: scores.seo },
  ];

  const metricItems = [
    { label: 'First Contentful Paint',   value: metrics.fcp },
    { label: 'Largest Contentful Paint', value: metrics.lcp },
    { label: 'Total Blocking Time',      value: metrics.tbt },
    { label: 'Cumulative Layout Shift',  value: metrics.cls },
    { label: 'Speed Index',              value: metrics.si },
    { label: 'Time to First Byte',       value: metrics.ttfb },
    { label: 'Time to Interactive',      value: metrics.tti },
  ];

  const scoreCards = scoreItems.map(item => `
    <div style="text-align:center;background:#1e1e1e;border-radius:12px;padding:20px 16px;flex:1;min-width:120px">
      <div style="font-size:52px;font-weight:700;color:${scoreColor(item.value)};line-height:1">${item.value ?? 'N/A'}</div>
      <div style="font-size:12px;color:#999;margin-top:8px">${item.label}</div>
    </div>
  `).join('');

  const metricRows = metricItems.map((m, i) => `
    <tr style="background:${i % 2 === 0 ? '#1a1a1a' : '#1e1e1e'}">
      <td style="padding:9px 16px;color:#ccc;font-size:13px">${m.label}</td>
      <td style="padding:9px 16px;color:#fff;font-size:13px;text-align:right;font-weight:500">${m.value ?? 'N/A'}</td>
    </tr>
  `).join('');

  return `<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<style>
  * { box-sizing: border-box; margin: 0; padding: 0; }
  body { background: #111; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Helvetica, sans-serif; padding: 32px; color: #fff; }
</style>
</head>
<body>
  <div style="font-size:11px;color:#4a9eff;text-transform:uppercase;letter-spacing:1px;margin-bottom:8px">PageSpeed Insights · ${strategy}</div>
  <h1 style="font-size:22px;font-weight:600;margin-bottom:4px">${domain}</h1>
  <div style="font-size:12px;color:#555;margin-bottom:28px">${apiUrl}</div>
  <div style="display:flex;gap:12px;margin-bottom:24px;flex-wrap:wrap">${scoreCards}</div>
  <table style="width:100%;border-collapse:collapse;border-radius:12px;overflow:hidden">
    <tbody>${metricRows}</tbody>
  </table>
  <div style="margin-top:14px;font-size:11px;color:#444">
    Generated by fm-audit-tool · ${new Date().toLocaleString()}
  </div>
</body>
</html>`;
}

// ── Call the PageSpeed API with a specific strategy ───────────────────────────
async function fetchPageSpeedData(domain, apiKey, strategy) {
  const url = new URL(API_ENDPOINT);
  url.searchParams.set('url', `https://${domain}`);
  url.searchParams.set('strategy', strategy);   // 'desktop' or 'mobile'
  if (apiKey) url.searchParams.set('key', apiKey);
  url.searchParams.append('category', 'PERFORMANCE');
  url.searchParams.append('category', 'ACCESSIBILITY');
  url.searchParams.append('category', 'BEST_PRACTICES');
  url.searchParams.append('category', 'SEO');

  const json = await fetchJson(url);

  // Surface API-level errors immediately instead of silently returning N/A
  if (json.error) {
    throw new Error(`PageSpeed API error ${json.error.code}: ${json.error.message}`);
  }
  if (!json.lighthouseResult) {
    throw new Error('No lighthouseResult in API response');
  }

  const lighthouse = json.lighthouseResult;
  const categories = lighthouse.categories || {};
  const audits     = lighthouse.audits || {};
  const crux       = json.loadingExperience?.metrics || {};

  const scores = {
    performance:   categories.performance       ? Math.round(categories.performance.score * 100)       : "N/A",
    accessibility: categories.accessibility     ? Math.round(categories.accessibility.score * 100)     : "N/A",
    bestPractices: categories["best-practices"] ? Math.round(categories["best-practices"].score * 100) : "N/A",
    seo:           categories.seo               ? Math.round(categories.seo.score * 100)               : "N/A",
  };

  const metrics = {
    fcp:  cleanValue(audits["first-contentful-paint"]?.displayValue)   || "N/A",
    lcp:  cleanValue(audits["largest-contentful-paint"]?.displayValue) || "N/A",
    tbt:  cleanValue(audits["total-blocking-time"]?.displayValue)      || "N/A",
    cls:  cleanValue(audits["cumulative-layout-shift"]?.displayValue)  || "N/A",
    ttfb: cleanValue(audits["time-to-first-byte"]?.displayValue)       || "N/A",
    si:   cleanValue(audits["speed-index"]?.displayValue)              || "N/A",
    tti:  cleanValue(audits["interactive"]?.displayValue)              || "N/A",
  };

  const cruxMetrics = {
    fcpCategory: crux.FIRST_CONTENTFUL_PAINT_MS?.category || "N/A",
    inpCategory: crux.INTERACTION_TO_NEXT_PAINT?.category || "N/A",
  };

  const resolvedStrategy = lighthouse.configSettings?.emulatedFormFactor?.toUpperCase() || strategy.toUpperCase();

  return { scores, metrics, cruxMetrics, strategy: resolvedStrategy, analysisTimestamp: json.analysisUTCTimestamp };
}

// ── Take screenshot of local HTML scorecard ───────────────────────────────────
async function takeScreenshot(domain, scores, metrics, strategy, apiUrl, paths, newTab, wait) {
  const htmlPath = path.join(paths.domainDir, '_pagespeed_card.html');
  const pngPath  = path.join(paths.imagesDir, 'pagespeed.png');

  try {
    fs.writeFileSync(htmlPath, buildScorecardHtml(domain, scores, metrics, strategy, apiUrl), 'utf8');

    const tab = await newTab();
    try {
      // file:// on Linux needs 3 slashes: file:///absolute/path
      const fileUrl = 'file://' + htmlPath;
      await tab.goto(fileUrl, { waitUntil: 'load', timeout: 15000 });
      await wait(400);
      await tab.screenshot({ path: pngPath, fullPage: true });
      return 'pagespeed.png';
    } finally {
      await tab.close();
      try { fs.unlinkSync(htmlPath); } catch (_) {}
    }
  } catch (err) {
    console.error(`   📈 Screenshot failed: ${err.message}`);
    return null;
  }
}

async function runPageSpeed(domain, context) {
  const { wait, newTab, paths } = context;
  const PAGESPEED_API_KEY = context.env.PAGESPEED_API_KEY || "";

  const apiUrl = `https://pagespeed.web.dev/report?url=https://${domain}`;

  // ── Strategy: try DESKTOP first (more reliable, less throttling).
  //   If that fails, retry with MOBILE as fallback.
  //   Previously no strategy was set at all, which defaulted to mobile
  //   and caused silent N/A failures on many sites.
  let apiData = null;
  let apiError = null;
  let usedStrategy = 'DESKTOP';

  for (const strategy of ['desktop', 'mobile']) {
    try {
      apiData = await fetchPageSpeedData(domain, PAGESPEED_API_KEY, strategy);
      usedStrategy = strategy.toUpperCase();
      break; // success — stop trying
    } catch (err) {
      console.error(`   📈 PageSpeed ${strategy} failed: ${err.message}`);
      apiError = err;
      apiData = null;
      // loop continues to try next strategy
    }
  }

  if (!apiData) {
    // Both strategies failed — return N/A with the actual error message visible
    return {
      status: "SUCCESS",
      data: {
        scores:      { performance: "N/A", accessibility: "N/A", bestPractices: "N/A", seo: "N/A" },
        metrics:     { fcp: "N/A", lcp: "N/A", tbt: "N/A", cls: "N/A", ttfb: "N/A", si: "N/A", tti: "N/A" },
        cruxMetrics: { fcpCategory: "N/A", inpCategory: "N/A" },
        strategy:    "FAILED",
      },
      error: apiError?.message || "Unknown error",
      errorCode: getErrorCode({ error: apiError?.message }),
      url: apiUrl,
      screenshot: null,
    };
  }

  // ── API succeeded — take local screenshot from the data ───────────────────
  const screenshot = await takeScreenshot(
    domain,
    apiData.scores,
    apiData.metrics,
    usedStrategy,
    apiUrl,
    paths,
    newTab,
    wait
  );

  return {
    status: "SUCCESS",
    data: apiData,
    error: null,
    errorCode: null,
    url: apiUrl,
    screenshot,
  };
}

module.exports = { runPageSpeed };