module.exports = {
  CSV_FIELDS: [
    "Domain",
    "Run_At",
    "Total_Time",
    "SSL_Status",
    "SSL_Error",
    "SSL_ErrorCode",
    "SSL_Grade",
    "SSL_Endpoints",
    "SSL_AllGrades",
    "SSL_URL",
    "SSL_Screenshot",
    "Sucuri_Status",
    "Sucuri_Error",
    "Sucuri_ErrorCode",
    "Sucuri_Overall",
    "Sucuri_Malware",
    "Sucuri_Blacklist",
    "Sucuri_URL",
    "Sucuri_Screenshot",
    "PageSpeed_Status",
    "PageSpeed_Error",
    "PageSpeed_ErrorCode",
    "PageSpeed_Performance",
    "PageSpeed_Accessibility",
    "PageSpeed_BestPractices",
    "PageSpeed_SEO",
    "PageSpeed_LCP",
    "PageSpeed_CLS",
    "PageSpeed_TBT",
    "PageSpeed_TTFB",
    "PageSpeed_FCP",
    "PageSpeed_URL",
    "PageSpeed_Screenshot",
    "Pingdom_Status",
    "Pingdom_Error",
    "Pingdom_ErrorCode",
    "Pingdom_Grade",
    "Pingdom_GradeLetter",
    "Pingdom_GradeNumber",
    "Pingdom_LoadTime",
    "Pingdom_PageSize",
    "Pingdom_Requests",
    "Pingdom_URL",
    "Pingdom_Screenshot",
    "DNS_Status",
    "DNS_Error",
    "DNS_ErrorCode",
    "DNS_Propagation",
    "DNS_TotalServers",
    "DNS_Propagated",
    "DNS_Failed",
    "DNS_PropagationRate",
    "DNS_URL",
    "DNS_Screenshot",
    "PageRank_Status",
    "PageRank_Error",
    "PageRank_ErrorCode",
    "PageRank_Integer",
    "PageRank_Decimal",
    "PageRank_Rank",
    "PageRank_URL",
    "Server_SPF_Status",
    "Server_SPF_Value",
    "Server_DMARC_Status",
    "Server_DMARC_Value",
    "Server_DKIM_Status",
    "Server_DKIM_Value",
    "Server_DomainBlacklist_Status",
    "Server_DomainBlacklist_Value",
    "Server_MX_Status",
    "Server_MX_Value",
    "Server_RBL_Status",
    "Server_RBL_Value",
    "Server_IP_Address",
    "Server_BrokenLinks_Status",
    "Server_BrokenLinks_Value",
    "Server_HTTP_Status",
    "Server_HTTP_Code",
    "Server_SSL_Status",
    "Server_SSL_Value",
    "IntoDNS_OverallHealth",
    "IntoDNS_ErrorCount",
    "IntoDNS_WarnCount",
    "IntoDNS_MX_Status",
    "IntoDNS_NS_Count",
    "IntoDNS_SOA_Serial",
    "IntoDNS_URL",
    "IntoDNS_Screenshot",
  ],

  SUMMARY_FIELDS: [
    "Domain",
    "Run_At",
    "Total_Time",
    "SSL_Status",
    "SSL_Grade",
    "SSL_Endpoints",
    "SSL_AllGrades",
    "SSL_URL",
    "SSL_Screenshot",
    "Sucuri_Status",
    "Sucuri_Overall",
    "Sucuri_Malware",
    "Sucuri_Blacklist",
    "Sucuri_URL",
    "Sucuri_Screenshot",
    "PageSpeed_Status",
    "PageSpeed_Performance",
    "PageSpeed_Accessibility",
    "PageSpeed_BestPractices",
    "PageSpeed_SEO",
    "PageSpeed_LCP",
    "PageSpeed_CLS",
    "PageSpeed_TBT",
    "PageSpeed_TTFB",
    "PageSpeed_FCP",
    "PageSpeed_URL",
    "PageSpeed_Screenshot",
    "Pingdom_Status",
    "Pingdom_Grade",
    "Pingdom_GradeLetter",
    "Pingdom_GradeNumber",
    "Pingdom_LoadTime",
    "Pingdom_PageSize",
    "Pingdom_Requests",
    "Pingdom_URL",
    "Pingdom_Screenshot",
    "DNS_Status",
    "DNS_Propagation",
    "DNS_TotalServers",
    "DNS_Propagated",
    "DNS_PropagationRate",
    "DNS_URL",
    "DNS_Screenshot",
    "PageRank_Status",
    "PageRank_Integer",
    "PageRank_Decimal",
    "PageRank_Rank",
    "PageRank_URL",
    "Server_SPF_Status",
    "Server_DMARC_Status",
    "Server_DKIM_Status",
    "Server_DomainBlacklist_Status",
    "Server_MX_Status",
    "Server_RBL_Status",
    "Server_IP_Address",
    "Server_BrokenLinks_Status",
    "Server_HTTP_Status",
    "Server_SSL_Status",
    "IntoDNS_OverallHealth",
    "IntoDNS_ErrorCount",
    "IntoDNS_WarnCount",
    "IntoDNS_MX_Status",
    "IntoDNS_NS_Count",
    "IntoDNS_SOA_Serial",
    "IntoDNS_URL",
    "IntoDNS_Screenshot",
  ],

  USER_AGENT: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",

  TIMEOUTS: {
    SSL_API_POLL: 20000,
    SSL_BROWSER: 360000,
    SCREENSHOT: 60000,
    PAGE_LOAD: 60000,
    SELECTOR_WAIT: 45000,
  },

  GRADE_ORDER: ["A+", "A", "A-", "B", "C", "D", "E", "F", "T", "M"],

  ENDPOINTS: {
    SSL_LABS_API: "https://api.ssllabs.com/api/v3/analyze",
    SSL_LABS_WEB: "https://www.ssllabs.com/ssltest/analyze.html",
    SUCURI_API: "https://sitecheck.sucuri.net/api/v3",
    PAGESPEED_API: "https://www.googleapis.com/pagespeedonline/v5/runPagespeed",
    PAGERANK_API: "https://openpagerank.com/api/v1.0/getPageRank",
    WHATSMYDNS: "https://www.whatsmydns.net/#A",
    DNS_CHECKER: "https://dnschecker.org/#A",
    PINGDOM: "https://tools.pingdom.com/",
  },

  SSH_CONFIG: {
    host: '65.49.9.241',
    port: '44781',
    user: 'ind'
  },

  SSL_LABS: {
    MAX_RETRIES: 4,
    MAX_API_POLLS: 15,
    POLL_INTERVAL: 8000,
    BASE_RETRY_DELAY: 15000,
  },

  SCREENSHOT_SELECTORS: {
    SUCURI: ".scan-results, .site-status, h2, body",
    PINGDOM: ".result-speed, .perf-grade, .results, body",
    DNS: "#resultsTable, .table, body",
  },

  
};